# Notebook 0: Wybranie opini z gry Final Fantasy XIII

**Autor:** Michał Bogdański

**Opis:** Projekt realizuje analizę sentymentu recenzji steam. Porównujemy podejście klasyczne (TF-IDF + SVM) z podejściem opartym na Transformerach (HerBERT).

**Źródło danych:** Zbiór `Steam Reviews` z kaggle.com – podział na oceny pozytywny i negatywne.

W tym notebooku:
1. Ładujemy dane
2. Tworzymy nowy plik csv z opiniami o grze Final Fantasy XIII

In [6]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\hardpc\pycharmprojects\analizasentymentusteam\.venv\lib\site-packages (3.0.2)
Requirement already satisfied: numpy>=2.3.3 in c:\users\hardpc\pycharmprojects\analizasentymentusteam\.venv\lib\site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\hardpc\pycharmprojects\analizasentymentusteam\.venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\hardpc\pycharmprojects\analizasentymentusteam\.venv\lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in c:\users\hardpc\pycharmprojects\analizasentymentusteam\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.1.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [6]:
import pandas as pd

## 2. Pobranie i załadowanie danych

Korzystamy ze zbioru `Steam Reviews` dostępnego na kaggle.com. Zbiór zawiera recenzje w języku angielskim gier na steam (pozytywne/negatywne).

In [12]:
df = pd.read_csv("steam_reviews.csv")
df = df.dropna(subset=['review_text', 'review_score'])
print(f"Liczba rekordów: {len(df)}")
print(f"Kolumny: {list(df.columns)}")
df.head()

Liczba rekordów: 6409801
Kolumny: ['app_id', 'app_name', 'review_text', 'review_score', 'review_votes']

,app_id,app_name,review_text,review_score,review_votes
0,10,Counter-Strike,Ruined my life.,1,0
1,10,Counter-Strike,This will be more of a ''my experience with th...,1,1
2,10,Counter-Strike,This game saved my virginity.,1,0
3,10,Counter-Strike,• Do you like original games? • Do you like ga...,1,0
4,10,Counter-Strike,"Easy to learn, hard to master.",1,1

In [13]:
df[df['app_name'] == 'FINAL FANTASY XIII']

,app_id,app_name,review_text,review_score,review_votes
3663649,292120,FINAL FANTASY XIII,This game has a tremendous polarizing effect o...,1,1
3663650,292120,FINAL FANTASY XIII,"From what I have gathered, this game is somewh...",1,1
3663651,292120,FINAL FANTASY XIII,It's really hard to talk about this game. I've...,-1,1
3663652,292120,FINAL FANTASY XIII,"ok, now i finally beat this game, time for a ...",1,1
3663653,292120,FINAL FANTASY XIII,This review is spoiler-free. First things f...,1,1
...,...,...,...,...,...
3667545,292120,FINAL FANTASY XIII,"The earlier issues were patched, now the game ...",1,0
3667546,292120,FINAL FANTASY XIII,I want to start by saying that I actually went...,-1,0
3667547,292120,FINAL FANTASY XIII,"Don't buy this game!!! First, I spent a good...",-1,0
3667548,292120,FINAL FANTASY XIII,stuttering problem and not a steady frame rate...,1,0
3667549,292120,FINAL FANTASY XIII,everything is excellent but the only one bad t...,1,0

In [14]:
df[df['app_name'] == 'FINAL FANTASY XIII'][['review_text', 'review_score']].to_csv('final_fantasy_XIII.csv', index=False)